Q1. What are the most common reasons for missing data in ETL pipelines?



- Missing data can occur in ETL pipelines for several reasons. One common reason is data entry errors, where users forget to enter values or leave fields empty. Another reason is system integration issues, where data coming from different systems may not match properly. Missing data can also occur due to technical failures, such as interrupted data transfers or system crashes. Sometimes privacy or business rules also prevent certain information from being stored, which leads to missing values in the dataset.

Q2. Why is blindly deleting rows with missing values considered a bad practice in ETL?

Blindly deleting rows with missing values is considered a bad practice because it can lead to loss of important data. If many rows are deleted, the dataset may become too small or biased. This can affect the accuracy of analysis and lead to incorrect conclusions. Instead of deleting rows without thinking, it is better to analyze why the data is missing and apply appropriate techniques such as imputation or data correction.

Q3. Explain the difference between:

Listwise deletion
column wisw deletion

Also mention one scenario where each is appropriate.

- Listwise deletion means removing entire rows from a dataset if they contain missing values. This method is useful when only a small number of rows have missing data and removing them does not affect the dataset significantly.

- Column deletion, on the other hand, means removing an entire column if it contains too many missing values and is not very useful for analysis.

- Example scenario:
Listwise deletion is suitable when only a few records are incomplete.
Column deletion is suitable when a column has a large number of missing values and cannot provide meaningful insights.

Q4. Why is median imputation preferred over mean imputation for skewed data such as income?

- Median imputation is preferred for skewed data because the mean can be heavily affected by extreme values or outliers. In datasets such as income, some individuals may earn extremely high salaries which can distort the mean. The median represents the middle value of the dataset and is less affected by outliers. Therefore, using the median provides a more realistic estimate for missing values in skewed datasets.

Q5. What is forward fill and in what type of dataset is it most useful?

- Forward fill is a technique used to handle missing values by filling them with the previous available value in the dataset. This method is commonly used in time-series data, such as stock prices, sales records, or sensor data, where the previous value is likely to remain valid until a new value appears.

- for example, if sales data for a particular day is missing, it can be filled with the sales value from the previous day.

Q6. Why should flagging missing values be done before imputation in an ETL workflow?

- Flagging missing values before imputation is important because it helps track which data was originally missing. When missing values are replaced with estimated values, the information about missing data can be lost. By creating a flag column, analysts can later identify which records were imputed and analyze patterns in missing data. This improves transparency and helps maintain data quality.

Q7. Consider a scenario where income is missing for many customers. How can this missingness itself provide business insights?

- Missing income values can provide useful insights about customer behavior. For example, customers may choose not to share income information due to privacy concerns or because they belong to certain demographic groups. If income is missing for a particular region or customer segment, it may indicate issues in data collection or customer trust. Businesses can analyze these patterns to improve data collection strategies or understand customer characteristics better.

Q8. Listwise Deletion

Remove all rows where Region is missing.

Tasks:

Identify affected rows

Show the dataset after deletion

Mention how many records were lost

In [1]:
import pandas as pd

In [2]:
data = {
    "Customer_ID":[101,102,103,104,105,106,107,108],
    "Name":["Rahul Mehta","Anjali Rao","Suresh Iyer","Neha Singh","Amit Verma","Karan Shah","Pooja Das","Riya Kapoor"],
    "City":["Mumbai","Bengaluru","Chennai","Delhi","Pune","Ahmedabad","Kolkata","Jaipur"],
    "Monthly_Sales":[12000,None,15000,None,18000,None,14000,16000],
    "Income":[65000,None,72000,None,58000,61000,None,69000],
    "Region":["West","South","South","North",None,"West","East","North"]
}

df = pd.DataFrame(data)

df

   Customer_ID         Name       City  Monthly_Sales   Income Region
0          101  Rahul Mehta     Mumbai        12000.0  65000.0   West
1          102   Anjali Rao  Bengaluru            NaN      NaN  South
2          103  Suresh Iyer    Chennai        15000.0  72000.0  South
3          104   Neha Singh      Delhi            NaN      NaN  North
4          105   Amit Verma       Pune        18000.0  58000.0   None
5          106   Karan Shah  Ahmedabad            NaN  61000.0   West
6          107    Pooja Das    Kolkata        14000.0      NaN   East
7          108  Riya Kapoor     Jaipur        16000.0  69000.0  North

In [3]:
df[df["Region"].isna()]

   Customer_ID        Name  City  Monthly_Sales   Income Region
4          105  Amit Verma  Pune        18000.0  58000.0   None

In [4]:
df_clean = df.dropna(subset=["Region"])

df_clean

   Customer_ID         Name       City  Monthly_Sales   Income Region
0          101  Rahul Mehta     Mumbai        12000.0  65000.0   West
1          102   Anjali Rao  Bengaluru            NaN      NaN  South
2          103  Suresh Iyer    Chennai        15000.0  72000.0  South
3          104   Neha Singh      Delhi            NaN      NaN  North
5          106   Karan Shah  Ahmedabad            NaN  61000.0   West
6          107    Pooja Das    Kolkata        14000.0      NaN   East
7          108  Riya Kapoor     Jaipur        16000.0  69000.0  North

In [5]:
original_rows = len(df)
new_rows = len(df_clean)

print("Records removed:", original_rows - new_rows)

Records removed: 1

Q9. Imputation

Handle missing values in Monthly_Sales using:

Forward Fill

Tasks:

Apply forward fill

Show before vs after values

Explain why forward fill is suitable here

In [6]:
df["Monthly_Sales"]

0    12000.0
1        NaN
2    15000.0
3        NaN
4    18000.0
5        NaN
6    14000.0
7    16000.0
Name: Monthly_Sales, dtype: float64

In [7]:
df["Monthly_Sales"] = df["Monthly_Sales"].ffill()

df

   Customer_ID         Name       City  Monthly_Sales   Income Region
0          101  Rahul Mehta     Mumbai        12000.0  65000.0   West
1          102   Anjali Rao  Bengaluru        12000.0      NaN  South
2          103  Suresh Iyer    Chennai        15000.0  72000.0  South
3          104   Neha Singh      Delhi        15000.0      NaN  North
4          105   Amit Verma       Pune        18000.0  58000.0   None
5          106   Karan Shah  Ahmedabad        18000.0  61000.0   West
6          107    Pooja Das    Kolkata        14000.0      NaN   East
7          108  Riya Kapoor     Jaipur        16000.0  69000.0  North

Q10. Flagging Missing Data

Create a flag column for missing Income.

Tasks:

Create Income_Missing_Flag (0 = present, 1 = missing)

Show updated dataset

Count how many customers have missing income

In [8]:
df["Income_Missing_Flag"] = df["Income"].isna().astype(int)

df

,Customer_ID,Name,City,Monthly_Sales,Income,Region,Income_Missing_Flag
0,101,Rahul Mehta,Mumbai,12000.0,65000.0,West,0
1,102,Anjali Rao,Bengaluru,12000.0,NaN,South,1
2,103,Suresh Iyer,Chennai,15000.0,72000.0,South,0
3,104,Neha Singh,Delhi,15000.0,NaN,North,1
4,105,Amit Verma,Pune,18000.0,58000.0,None,0
5,106,Karan Shah,Ahmedabad,18000.0,61000.0,West,0
6,107,Pooja Das,Kolkata,14000.0,NaN,East,1
7,108,Riya Kapoor,Jaipur,16000.0,69000.0,North,0

In [9]:
df["Income_Missing_Flag"].sum()

np.int64(3)